name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: gopath/src/github.com/katydid/parser-gogo-proto
    - name: Checkout gogoprotobuf
      uses: actions/checkout@v4
      with:
        repository: gogo/protobuf
        path: gopath/src/github.com/gogo/protobuf
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
    - name: Fetch dependencies
      run: |
        cd gopath/src/github.com/katydid/parser-gogo-proto
        go mod download -x
    - name: Install tools
      run: |
        cd gopath/src/github.com/katydid/parser-gogo-proto
        go install -x github.com/awalterschulze/checklicense
        go install -x github.com/gogo/protobuf/protoc-gen-gogo
    - name: Setup protoc
      run: |
        cd gopath/src/github.com/katydid/parser-gogo-proto
        ./install_protoc.sh
    - name: Protoc version
      run: |
        cd gopath/src/github.com/katydid/parser-gogo-proto
        PATH=$HOME/bin:$PATH protoc --version
    - name: env
      run: env && go env && pwd
    - name: tree
      run: tree
    - name: Generate
      run: |
        cd gopath/src/github.com/katydid/parser-gogo-proto
        PATH=$HOME/bin:$PATH make regenerate
    - name: Build
      run: |
        cd gopath/src/github.com/katydid/parser-gogo-proto
        make build
    - name: Test
      run: |
        cd gopath/src/github.com/katydid/parser-gogo-proto
        make test
    - name: Vet
      run: |
        cd gopath/src/github.com/katydid/parser-gogo-proto
        make vet
    - name: Checklicencse
      run: |
        cd gopath/src/github.com/katydid/parser-gogo-proto
        make checklicense
    - name: Diff
      run: |
        cd gopath/src/github.com/katydid/parser-gogo-proto
        make diff
